name: LUMA API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run Tests
        run: mvn clean test

      - name: Install Allure commandline
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Allure CLI globally
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure HTML report
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      - name: Deploy to GitHub Pages
        uses: peace iris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GH_TOKEN }}
            publish_dir: ./target/allure-report
